# Generated by Django 4.2.16 on 2025-02-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myexpenses',
            name='date',
            field=models.DateField(),
        ),
    ]
