# Generated by Django 4.2.16 on 2025-02-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_myexpenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myexpenses',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
